DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS AUTHORS;

CREATE TABLE GENRES(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE AUTHORS(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE BOOKS(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(255),
    PUBLISHED DATE,
    GENRE_ID BIGINT,
    AUTHOR_ID BIGINT,
    FOREIGN KEY (GENRE_ID) REFERENCES GENRES(ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID)
);